# This is the configuration file for the Genie Bot application within production environment (Databricks Apps).
# This is for manual deployment via UI.
command:
  - streamlit
  - run
  - genie_bot.py

env:
  - name: "GENIE_SPACE" # Genie Space ID
    valueFrom: "genie-space" # valueFrom recovers the value stored in the App's resources configuration
  - name: "DATABRICKS_HOST"
    valueFrom: "databricks-host"
  - name: "DATABRICKS_TOKEN"
    valueFrom: "databricks-token"

# - name: "SERVING_ENDPOINT_NAME"
#   valueFrom: "serving-endpoint"
# - name: "UC_VOLUME"
#   valueFrom: "uc-volume"
